services:
  sim-sim-gateway:
    image: ghcr.io/simsimopen/sim-sim-api-gateway:latest
    container_name: sim-sim-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
      - SPRING_PROFILES_ACTIVE=prod
    command: [
      "java",
      "-Duser.timezone=Asia/Tashkent",
      "-Xms128m",
      "-Xmx384m",
      "-XX:+UseG1GC",
      "-XX:MaxGCPauseMillis=200",
      "-jar",
      "app.jar"
    ]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    restart: always
    networks:
      - simsim

networks:
  simsim:
    name: simsim
    external: true